### ISSUE TITLE
Durafetch Usage Scope

### ISSUE THREAD

**Issue by killrocksfun** [emadda/durafetch-server#1]
Currently I am writing a quiz app that uses websocket and durable objects, similar to a lite kahoot. Based on the docs, I would be able to access the quiz answers in sqlite table if its stored in the session's durable objects ?

**Comment by emadda** [comment]
Yes, anything you write via the [Durable Object storage API ](https://developers.cloudflare.com/workers/runtime-apis/durable-objects/#transactional-storage-api)(put, delete) will be in the SQLite db on the machine running the CLI.
